###
GET http://127.0.0.1:5000/ping

###
POST http://127.0.0.1:5000/api/url
Content-Type: application/json

{
    "original_url": "https://some_url/page/122"
}

###
GET http://127.0.0.1:5000/EI3Ava

###
GET http://127.0.0.1:5000/api/manual_url_deactivation

###
GET http://127.0.0.1:5000/api/nearest/5

###
GET http://127.0.0.1:5000/api/distinct_origins_from_storage

###
GET http://127.0.0.1:5000/api/origin_statistic_by_logs